//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.13 at 04:36:46 PM EDT 
//


package org.mujoco.xml.MuJoCoDefault;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.Copyable;
import com.kscs.util.jaxb.PartialCopyable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import com.kscs.util.jaxb.PropertyVisitor;
import org.mujoco.xml.attributetypes.CameramodeType;


/**
 * <p>Java class for cameraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cameraType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="mode" type="{attributeTypes}cameramodeType" default="fixed" /&gt;
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fovy" type="{http://www.w3.org/2001/XMLSchema}decimal" default="45" /&gt;
 *       &lt;attribute name="ipd" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.068" /&gt;
 *       &lt;attribute name="pos" type="{attributeTypes}threeRealsType" default="0 0 0" /&gt;
 *       &lt;attribute name="quat" type="{attributeTypes}fourRealsType" default="1 0 0 0" /&gt;
 *       &lt;attribute name="axisangle" type="{attributeTypes}fourRealsType" /&gt;
 *       &lt;attribute name="euler" type="{attributeTypes}threeRealsType" /&gt;
 *       &lt;attribute name="xyaxes" type="{attributeTypes}sixRealsType" /&gt;
 *       &lt;attribute name="zaxis" type="{attributeTypes}threeRealsType" /&gt;
 *       &lt;attribute name="user" type="{attributeTypes}infRealsType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cameraType")
public class CameraType implements Cloneable, Copyable, PartialCopyable
{

    @XmlAttribute(name = "mode")
    protected CameramodeType mode;
    @XmlAttribute(name = "target")
    protected String target;
    @XmlAttribute(name = "fovy")
    protected BigDecimal fovy;
    @XmlAttribute(name = "ipd")
    protected BigDecimal ipd;
    @XmlAttribute(name = "pos")
    protected String pos;
    @XmlAttribute(name = "quat")
    protected String quat;
    @XmlAttribute(name = "axisangle")
    protected String axisangle;
    @XmlAttribute(name = "euler")
    protected String euler;
    @XmlAttribute(name = "xyaxes")
    protected String xyaxes;
    @XmlAttribute(name = "zaxis")
    protected String zaxis;
    @XmlAttribute(name = "user")
    protected String user;
    protected final transient VetoableChangeSupport vetoableChange__Support = new VetoableChangeSupport(this);
    protected final transient PropertyChangeSupport propertyChange__Support = new PropertyChangeSupport(this);

    /**
     * Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
     * 
     */
    public CameraType() {
        // Generated by copy-constructor plugin, JAXB requires public no-arg constructor.
    }

    /**
     * Instantiates a CameraType copying the state of another CameraType
     * 
     * @param _other
     *     The original CameraType from which to copy state.
     */
    public CameraType(final CameraType _other) {
        this.mode = _other.mode;
        this.target = _other.target;
        this.fovy = _other.fovy;
        this.ipd = _other.ipd;
        this.pos = _other.pos;
        this.quat = _other.quat;
        this.axisangle = _other.axisangle;
        this.euler = _other.euler;
        this.xyaxes = _other.xyaxes;
        this.zaxis = _other.zaxis;
        this.user = _other.user;
    }

    /**
     * Instantiates a CameraType copying the state of another CameraType
     * 
     * @param _propertyTreeUse
     *     Meaning of the {@link PropertyPath}: Exclude or include members contained in property path.
     * @param _propertyTree
     *     A restricting {@link PropertyPath} that defines which nodes of the source object tree should actually be copied.
     * @param _other
     *     The original CameraType from which to copy state.
     */
    public CameraType(final CameraType _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree modePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(modePropertyTree!= null):((modePropertyTree == null)||(!modePropertyTree.isLeaf())))) {
            this.mode = _other.mode;
        }
        final PropertyTree targetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("target"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(targetPropertyTree!= null):((targetPropertyTree == null)||(!targetPropertyTree.isLeaf())))) {
            this.target = _other.target;
        }
        final PropertyTree fovyPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("fovy"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(fovyPropertyTree!= null):((fovyPropertyTree == null)||(!fovyPropertyTree.isLeaf())))) {
            this.fovy = _other.fovy;
        }
        final PropertyTree ipdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ipd"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ipdPropertyTree!= null):((ipdPropertyTree == null)||(!ipdPropertyTree.isLeaf())))) {
            this.ipd = _other.ipd;
        }
        final PropertyTree posPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("pos"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(posPropertyTree!= null):((posPropertyTree == null)||(!posPropertyTree.isLeaf())))) {
            this.pos = _other.pos;
        }
        final PropertyTree quatPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("quat"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(quatPropertyTree!= null):((quatPropertyTree == null)||(!quatPropertyTree.isLeaf())))) {
            this.quat = _other.quat;
        }
        final PropertyTree axisanglePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("axisangle"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(axisanglePropertyTree!= null):((axisanglePropertyTree == null)||(!axisanglePropertyTree.isLeaf())))) {
            this.axisangle = _other.axisangle;
        }
        final PropertyTree eulerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("euler"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(eulerPropertyTree!= null):((eulerPropertyTree == null)||(!eulerPropertyTree.isLeaf())))) {
            this.euler = _other.euler;
        }
        final PropertyTree xyaxesPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("xyaxes"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(xyaxesPropertyTree!= null):((xyaxesPropertyTree == null)||(!xyaxesPropertyTree.isLeaf())))) {
            this.xyaxes = _other.xyaxes;
        }
        final PropertyTree zaxisPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("zaxis"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(zaxisPropertyTree!= null):((zaxisPropertyTree == null)||(!zaxisPropertyTree.isLeaf())))) {
            this.zaxis = _other.zaxis;
        }
        final PropertyTree userPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("user"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(userPropertyTree!= null):((userPropertyTree == null)||(!userPropertyTree.isLeaf())))) {
            this.user = _other.user;
        }
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link CameramodeType }
     *     
     */
    public CameramodeType getMode() {
        if (mode == null) {
            return CameramodeType.FIXED;
        } else {
            return mode;
        }
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Gets the value of the fovy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFovy() {
        if (fovy == null) {
            return new BigDecimal("45");
        } else {
            return fovy;
        }
    }

    /**
     * Gets the value of the ipd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIpd() {
        if (ipd == null) {
            return new BigDecimal("0.068");
        } else {
            return ipd;
        }
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPos() {
        if (pos == null) {
            return "0 0 0";
        } else {
            return pos;
        }
    }

    /**
     * Gets the value of the quat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuat() {
        if (quat == null) {
            return "1 0 0 0";
        } else {
            return quat;
        }
    }

    /**
     * Gets the value of the axisangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxisangle() {
        return axisangle;
    }

    /**
     * Gets the value of the euler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuler() {
        return euler;
    }

    /**
     * Gets the value of the xyaxes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXyaxes() {
        return xyaxes;
    }

    /**
     * Gets the value of the zaxis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZaxis() {
        return zaxis;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    public void addVetoableChangeListener(final VetoableChangeListener vetoableChangeListener) {
        this.vetoableChange__Support.addVetoableChangeListener(vetoableChangeListener);
    }

    public void removeVetoableChangeListener(final VetoableChangeListener vetoableChangeListener) {
        this.vetoableChange__Support.removeVetoableChangeListener(vetoableChangeListener);
    }

    public CameraType withVetoableChangeListener(final VetoableChangeListener vetoableChangeListener) {
        addVetoableChangeListener(vetoableChangeListener);
        return this;
    }

    public void addPropertyChangeListener(final PropertyChangeListener propertyChangeListener) {
        this.propertyChange__Support.addPropertyChangeListener(propertyChangeListener);
    }

    public void removePropertyChangeListener(final PropertyChangeListener propertyChangeListener) {
        this.propertyChange__Support.removePropertyChangeListener(propertyChangeListener);
    }

    public CameraType withPropertyChangeListener(final PropertyChangeListener propertyChangeListener) {
        addPropertyChangeListener(propertyChangeListener);
        return this;
    }

    public void setMode(final CameramodeType value) {
        final CameramodeType __oldValue = this.mode;
        try {
            this.vetoableChange__Support.fireVetoableChange("mode", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.mode = value;
        this.propertyChange__Support.firePropertyChange("mode", __oldValue, value);
    }

    public void setTarget(final String value) {
        final String __oldValue = this.target;
        try {
            this.vetoableChange__Support.fireVetoableChange("target", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.target = value;
        this.propertyChange__Support.firePropertyChange("target", __oldValue, value);
    }

    public void setFovy(final BigDecimal value) {
        final BigDecimal __oldValue = this.fovy;
        try {
            this.vetoableChange__Support.fireVetoableChange("fovy", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.fovy = value;
        this.propertyChange__Support.firePropertyChange("fovy", __oldValue, value);
    }

    public void setIpd(final BigDecimal value) {
        final BigDecimal __oldValue = this.ipd;
        try {
            this.vetoableChange__Support.fireVetoableChange("ipd", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.ipd = value;
        this.propertyChange__Support.firePropertyChange("ipd", __oldValue, value);
    }

    public void setPos(final String value) {
        final String __oldValue = this.pos;
        try {
            this.vetoableChange__Support.fireVetoableChange("pos", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.pos = value;
        this.propertyChange__Support.firePropertyChange("pos", __oldValue, value);
    }

    public void setQuat(final String value) {
        final String __oldValue = this.quat;
        try {
            this.vetoableChange__Support.fireVetoableChange("quat", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.quat = value;
        this.propertyChange__Support.firePropertyChange("quat", __oldValue, value);
    }

    public void setAxisangle(final String value) {
        final String __oldValue = this.axisangle;
        try {
            this.vetoableChange__Support.fireVetoableChange("axisangle", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.axisangle = value;
        this.propertyChange__Support.firePropertyChange("axisangle", __oldValue, value);
    }

    public void setEuler(final String value) {
        final String __oldValue = this.euler;
        try {
            this.vetoableChange__Support.fireVetoableChange("euler", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.euler = value;
        this.propertyChange__Support.firePropertyChange("euler", __oldValue, value);
    }

    public void setXyaxes(final String value) {
        final String __oldValue = this.xyaxes;
        try {
            this.vetoableChange__Support.fireVetoableChange("xyaxes", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.xyaxes = value;
        this.propertyChange__Support.firePropertyChange("xyaxes", __oldValue, value);
    }

    public void setZaxis(final String value) {
        final String __oldValue = this.zaxis;
        try {
            this.vetoableChange__Support.fireVetoableChange("zaxis", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.zaxis = value;
        this.propertyChange__Support.firePropertyChange("zaxis", __oldValue, value);
    }

    public void setUser(final String value) {
        final String __oldValue = this.user;
        try {
            this.vetoableChange__Support.fireVetoableChange("user", __oldValue, value);
        } catch (PropertyVetoException x) {
            throw new RuntimeException(x);
        }
        this.user = value;
        this.propertyChange__Support.firePropertyChange("user", __oldValue, value);
    }

    @Override
    public CameraType clone() {
        final CameraType _newObject;
        try {
            _newObject = ((CameraType) super.clone());
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
        return _newObject;
    }

    @Override
    public CameraType createCopy() {
        final CameraType _newObject;
        try {
            _newObject = ((CameraType) super.clone());
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
        _newObject.mode = this.mode;
        _newObject.target = this.target;
        _newObject.fovy = this.fovy;
        _newObject.ipd = this.ipd;
        _newObject.pos = this.pos;
        _newObject.quat = this.quat;
        _newObject.axisangle = this.axisangle;
        _newObject.euler = this.euler;
        _newObject.xyaxes = this.xyaxes;
        _newObject.zaxis = this.zaxis;
        _newObject.user = this.user;
        return _newObject;
    }

    @Override
    public CameraType createCopy(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final CameraType _newObject;
        try {
            _newObject = ((CameraType) super.clone());
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
        final PropertyTree modePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(modePropertyTree!= null):((modePropertyTree == null)||(!modePropertyTree.isLeaf())))) {
            _newObject.mode = this.mode;
        }
        final PropertyTree targetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("target"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(targetPropertyTree!= null):((targetPropertyTree == null)||(!targetPropertyTree.isLeaf())))) {
            _newObject.target = this.target;
        }
        final PropertyTree fovyPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("fovy"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(fovyPropertyTree!= null):((fovyPropertyTree == null)||(!fovyPropertyTree.isLeaf())))) {
            _newObject.fovy = this.fovy;
        }
        final PropertyTree ipdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ipd"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ipdPropertyTree!= null):((ipdPropertyTree == null)||(!ipdPropertyTree.isLeaf())))) {
            _newObject.ipd = this.ipd;
        }
        final PropertyTree posPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("pos"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(posPropertyTree!= null):((posPropertyTree == null)||(!posPropertyTree.isLeaf())))) {
            _newObject.pos = this.pos;
        }
        final PropertyTree quatPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("quat"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(quatPropertyTree!= null):((quatPropertyTree == null)||(!quatPropertyTree.isLeaf())))) {
            _newObject.quat = this.quat;
        }
        final PropertyTree axisanglePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("axisangle"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(axisanglePropertyTree!= null):((axisanglePropertyTree == null)||(!axisanglePropertyTree.isLeaf())))) {
            _newObject.axisangle = this.axisangle;
        }
        final PropertyTree eulerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("euler"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(eulerPropertyTree!= null):((eulerPropertyTree == null)||(!eulerPropertyTree.isLeaf())))) {
            _newObject.euler = this.euler;
        }
        final PropertyTree xyaxesPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("xyaxes"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(xyaxesPropertyTree!= null):((xyaxesPropertyTree == null)||(!xyaxesPropertyTree.isLeaf())))) {
            _newObject.xyaxes = this.xyaxes;
        }
        final PropertyTree zaxisPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("zaxis"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(zaxisPropertyTree!= null):((zaxisPropertyTree == null)||(!zaxisPropertyTree.isLeaf())))) {
            _newObject.zaxis = this.zaxis;
        }
        final PropertyTree userPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("user"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(userPropertyTree!= null):((userPropertyTree == null)||(!userPropertyTree.isLeaf())))) {
            _newObject.user = this.user;
        }
        return _newObject;
    }

    @Override
    public CameraType copyExcept(final PropertyTree _propertyTree) {
        return createCopy(_propertyTree, PropertyTreeUse.EXCLUDE);
    }

    @Override
    public CameraType copyOnly(final PropertyTree _propertyTree) {
        return createCopy(_propertyTree, PropertyTreeUse.INCLUDE);
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final CameraType.Builder<_B> _other) {
        _other.mode = this.mode;
        _other.target = this.target;
        _other.fovy = this.fovy;
        _other.ipd = this.ipd;
        _other.pos = this.pos;
        _other.quat = this.quat;
        _other.axisangle = this.axisangle;
        _other.euler = this.euler;
        _other.xyaxes = this.xyaxes;
        _other.zaxis = this.zaxis;
        _other.user = this.user;
    }

    public<_B >CameraType.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new CameraType.Builder<_B>(_parentBuilder, this, true);
    }

    public CameraType.Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static CameraType.Builder<Void> builder() {
        return new CameraType.Builder<Void>(null, null, false);
    }

    public static<_B >CameraType.Builder<_B> copyOf(final CameraType _other) {
        final CameraType.Builder<_B> _newBuilder = new CameraType.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final CameraType.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree modePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(modePropertyTree!= null):((modePropertyTree == null)||(!modePropertyTree.isLeaf())))) {
            _other.mode = this.mode;
        }
        final PropertyTree targetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("target"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(targetPropertyTree!= null):((targetPropertyTree == null)||(!targetPropertyTree.isLeaf())))) {
            _other.target = this.target;
        }
        final PropertyTree fovyPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("fovy"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(fovyPropertyTree!= null):((fovyPropertyTree == null)||(!fovyPropertyTree.isLeaf())))) {
            _other.fovy = this.fovy;
        }
        final PropertyTree ipdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ipd"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ipdPropertyTree!= null):((ipdPropertyTree == null)||(!ipdPropertyTree.isLeaf())))) {
            _other.ipd = this.ipd;
        }
        final PropertyTree posPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("pos"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(posPropertyTree!= null):((posPropertyTree == null)||(!posPropertyTree.isLeaf())))) {
            _other.pos = this.pos;
        }
        final PropertyTree quatPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("quat"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(quatPropertyTree!= null):((quatPropertyTree == null)||(!quatPropertyTree.isLeaf())))) {
            _other.quat = this.quat;
        }
        final PropertyTree axisanglePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("axisangle"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(axisanglePropertyTree!= null):((axisanglePropertyTree == null)||(!axisanglePropertyTree.isLeaf())))) {
            _other.axisangle = this.axisangle;
        }
        final PropertyTree eulerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("euler"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(eulerPropertyTree!= null):((eulerPropertyTree == null)||(!eulerPropertyTree.isLeaf())))) {
            _other.euler = this.euler;
        }
        final PropertyTree xyaxesPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("xyaxes"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(xyaxesPropertyTree!= null):((xyaxesPropertyTree == null)||(!xyaxesPropertyTree.isLeaf())))) {
            _other.xyaxes = this.xyaxes;
        }
        final PropertyTree zaxisPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("zaxis"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(zaxisPropertyTree!= null):((zaxisPropertyTree == null)||(!zaxisPropertyTree.isLeaf())))) {
            _other.zaxis = this.zaxis;
        }
        final PropertyTree userPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("user"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(userPropertyTree!= null):((userPropertyTree == null)||(!userPropertyTree.isLeaf())))) {
            _other.user = this.user;
        }
    }

    public<_B >CameraType.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new CameraType.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public CameraType.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B >CameraType.Builder<_B> copyOf(final CameraType _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final CameraType.Builder<_B> _newBuilder = new CameraType.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static CameraType.Builder<Void> copyExcept(final CameraType _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static CameraType.Builder<Void> copyOnly(final CameraType _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public CameraType visit(final PropertyVisitor _visitor_) {
        _visitor_.visit(this);
        return this;
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        private CameramodeType mode;
        private String target;
        private BigDecimal fovy;
        private BigDecimal ipd;
        private String pos;
        private String quat;
        private String axisangle;
        private String euler;
        private String xyaxes;
        private String zaxis;
        private String user;

        public Builder(final _B _parentBuilder, final CameraType _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                this.mode = _other.mode;
                this.target = _other.target;
                this.fovy = _other.fovy;
                this.ipd = _other.ipd;
                this.pos = _other.pos;
                this.quat = _other.quat;
                this.axisangle = _other.axisangle;
                this.euler = _other.euler;
                this.xyaxes = _other.xyaxes;
                this.zaxis = _other.zaxis;
                this.user = _other.user;
            }
        }

        public Builder(final _B _parentBuilder, final CameraType _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                final PropertyTree modePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mode"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(modePropertyTree!= null):((modePropertyTree == null)||(!modePropertyTree.isLeaf())))) {
                    this.mode = _other.mode;
                }
                final PropertyTree targetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("target"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(targetPropertyTree!= null):((targetPropertyTree == null)||(!targetPropertyTree.isLeaf())))) {
                    this.target = _other.target;
                }
                final PropertyTree fovyPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("fovy"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(fovyPropertyTree!= null):((fovyPropertyTree == null)||(!fovyPropertyTree.isLeaf())))) {
                    this.fovy = _other.fovy;
                }
                final PropertyTree ipdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ipd"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ipdPropertyTree!= null):((ipdPropertyTree == null)||(!ipdPropertyTree.isLeaf())))) {
                    this.ipd = _other.ipd;
                }
                final PropertyTree posPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("pos"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(posPropertyTree!= null):((posPropertyTree == null)||(!posPropertyTree.isLeaf())))) {
                    this.pos = _other.pos;
                }
                final PropertyTree quatPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("quat"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(quatPropertyTree!= null):((quatPropertyTree == null)||(!quatPropertyTree.isLeaf())))) {
                    this.quat = _other.quat;
                }
                final PropertyTree axisanglePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("axisangle"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(axisanglePropertyTree!= null):((axisanglePropertyTree == null)||(!axisanglePropertyTree.isLeaf())))) {
                    this.axisangle = _other.axisangle;
                }
                final PropertyTree eulerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("euler"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(eulerPropertyTree!= null):((eulerPropertyTree == null)||(!eulerPropertyTree.isLeaf())))) {
                    this.euler = _other.euler;
                }
                final PropertyTree xyaxesPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("xyaxes"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(xyaxesPropertyTree!= null):((xyaxesPropertyTree == null)||(!xyaxesPropertyTree.isLeaf())))) {
                    this.xyaxes = _other.xyaxes;
                }
                final PropertyTree zaxisPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("zaxis"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(zaxisPropertyTree!= null):((zaxisPropertyTree == null)||(!zaxisPropertyTree.isLeaf())))) {
                    this.zaxis = _other.zaxis;
                }
                final PropertyTree userPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("user"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(userPropertyTree!= null):((userPropertyTree == null)||(!userPropertyTree.isLeaf())))) {
                    this.user = _other.user;
                }
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends CameraType >_P init(final _P _product) {
            _product.mode = this.mode;
            _product.target = this.target;
            _product.fovy = this.fovy;
            _product.ipd = this.ipd;
            _product.pos = this.pos;
            _product.quat = this.quat;
            _product.axisangle = this.axisangle;
            _product.euler = this.euler;
            _product.xyaxes = this.xyaxes;
            _product.zaxis = this.zaxis;
            _product.user = this.user;
            return _product;
        }

        /**
         * Sets the new value of "mode" (any previous value will be replaced)
         * 
         * @param mode
         *     New value of the "mode" property.
         */
        public CameraType.Builder<_B> withMode(final CameramodeType mode) {
            this.mode = mode;
            return this;
        }

        /**
         * Sets the new value of "target" (any previous value will be replaced)
         * 
         * @param target
         *     New value of the "target" property.
         */
        public CameraType.Builder<_B> withTarget(final String target) {
            this.target = target;
            return this;
        }

        /**
         * Sets the new value of "fovy" (any previous value will be replaced)
         * 
         * @param fovy
         *     New value of the "fovy" property.
         */
        public CameraType.Builder<_B> withFovy(final BigDecimal fovy) {
            this.fovy = fovy;
            return this;
        }

        /**
         * Sets the new value of "ipd" (any previous value will be replaced)
         * 
         * @param ipd
         *     New value of the "ipd" property.
         */
        public CameraType.Builder<_B> withIpd(final BigDecimal ipd) {
            this.ipd = ipd;
            return this;
        }

        /**
         * Sets the new value of "pos" (any previous value will be replaced)
         * 
         * @param pos
         *     New value of the "pos" property.
         */
        public CameraType.Builder<_B> withPos(final String pos) {
            this.pos = pos;
            return this;
        }

        /**
         * Sets the new value of "quat" (any previous value will be replaced)
         * 
         * @param quat
         *     New value of the "quat" property.
         */
        public CameraType.Builder<_B> withQuat(final String quat) {
            this.quat = quat;
            return this;
        }

        /**
         * Sets the new value of "axisangle" (any previous value will be replaced)
         * 
         * @param axisangle
         *     New value of the "axisangle" property.
         */
        public CameraType.Builder<_B> withAxisangle(final String axisangle) {
            this.axisangle = axisangle;
            return this;
        }

        /**
         * Sets the new value of "euler" (any previous value will be replaced)
         * 
         * @param euler
         *     New value of the "euler" property.
         */
        public CameraType.Builder<_B> withEuler(final String euler) {
            this.euler = euler;
            return this;
        }

        /**
         * Sets the new value of "xyaxes" (any previous value will be replaced)
         * 
         * @param xyaxes
         *     New value of the "xyaxes" property.
         */
        public CameraType.Builder<_B> withXyaxes(final String xyaxes) {
            this.xyaxes = xyaxes;
            return this;
        }

        /**
         * Sets the new value of "zaxis" (any previous value will be replaced)
         * 
         * @param zaxis
         *     New value of the "zaxis" property.
         */
        public CameraType.Builder<_B> withZaxis(final String zaxis) {
            this.zaxis = zaxis;
            return this;
        }

        /**
         * Sets the new value of "user" (any previous value will be replaced)
         * 
         * @param user
         *     New value of the "user" property.
         */
        public CameraType.Builder<_B> withUser(final String user) {
            this.user = user;
            return this;
        }

        @Override
        public CameraType build() {
            return this.init(new CameraType());
        }

        public CameraType.Builder<_B> copyOf(final CameraType _other) {
            _other.copyTo(this);
            return this;
        }

        public CameraType.Builder<_B> copyOf(final CameraType.Builder _other) {
            return copyOf(_other.build());
        }

    }

    public static class PropInfo {

        public final static transient String MODE = "mode";
        public final static transient String TARGET = "target";
        public final static transient String FOVY = "fovy";
        public final static transient String IPD = "ipd";
        public final static transient String POS = "pos";
        public final static transient String QUAT = "quat";
        public final static transient String AXISANGLE = "axisangle";
        public final static transient String EULER = "euler";
        public final static transient String XYAXES = "xyaxes";
        public final static transient String ZAXIS = "zaxis";
        public final static transient String USER = "user";

    }

    public static class Select
        extends CameraType.Selector<CameraType.Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static CameraType.Select _root() {
            return new CameraType.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> mode = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> target = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> fovy = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> ipd = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> pos = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> quat = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> axisangle = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> euler = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> xyaxes = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> zaxis = null;
        private com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> user = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.mode!= null) {
                products.put("mode", this.mode.init());
            }
            if (this.target!= null) {
                products.put("target", this.target.init());
            }
            if (this.fovy!= null) {
                products.put("fovy", this.fovy.init());
            }
            if (this.ipd!= null) {
                products.put("ipd", this.ipd.init());
            }
            if (this.pos!= null) {
                products.put("pos", this.pos.init());
            }
            if (this.quat!= null) {
                products.put("quat", this.quat.init());
            }
            if (this.axisangle!= null) {
                products.put("axisangle", this.axisangle.init());
            }
            if (this.euler!= null) {
                products.put("euler", this.euler.init());
            }
            if (this.xyaxes!= null) {
                products.put("xyaxes", this.xyaxes.init());
            }
            if (this.zaxis!= null) {
                products.put("zaxis", this.zaxis.init());
            }
            if (this.user!= null) {
                products.put("user", this.user.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> mode() {
            return ((this.mode == null)?this.mode = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "mode"):this.mode);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> target() {
            return ((this.target == null)?this.target = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "target"):this.target);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> fovy() {
            return ((this.fovy == null)?this.fovy = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "fovy"):this.fovy);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> ipd() {
            return ((this.ipd == null)?this.ipd = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "ipd"):this.ipd);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> pos() {
            return ((this.pos == null)?this.pos = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "pos"):this.pos);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> quat() {
            return ((this.quat == null)?this.quat = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "quat"):this.quat);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> axisangle() {
            return ((this.axisangle == null)?this.axisangle = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "axisangle"):this.axisangle);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> euler() {
            return ((this.euler == null)?this.euler = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "euler"):this.euler);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> xyaxes() {
            return ((this.xyaxes == null)?this.xyaxes = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "xyaxes"):this.xyaxes);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> zaxis() {
            return ((this.zaxis == null)?this.zaxis = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "zaxis"):this.zaxis);
        }

        public com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>> user() {
            return ((this.user == null)?this.user = new com.kscs.util.jaxb.Selector<TRoot, CameraType.Selector<TRoot, TParent>>(this._root, this, "user"):this.user);
        }

    }

}
