/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mujoco.java;

import org.junit.Test;
import org.mujoco.MuJoCoLib;

import static org.junit.Assert.*;

public class MuJoColibTest {
    @Test public void mujocoJNILoadTest() {
        MuJoCoLib lib = new MuJoCoLib();
        
        System.out.println("Starting "+MuJoCoLib.mj_versionString().getString());
    }
}
