//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.14 at 04:25:33 PM EST 
//


package org.mujoco.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.mujoco.xml.body.BodyType;
import org.mujoco.xml.body.CameraType;
import org.mujoco.xml.body.CompositeType;
import org.mujoco.xml.body.CompositegeomType;
import org.mujoco.xml.body.CompositejointType;
import org.mujoco.xml.body.CompositesiteType;
import org.mujoco.xml.body.GeomType;
import org.mujoco.xml.body.InertialType;
import org.mujoco.xml.body.JointType;
import org.mujoco.xml.body.LightType;
import org.mujoco.xml.body.PinType;
import org.mujoco.xml.body.SiteType;
import org.mujoco.xml.body.SkinType;
import org.mujoco.xml.body.TendonType;
import org.mujoco.xml.root.IncludeType;


/**
 * <p>Java class for bodyarchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyarchType">
 *   &lt;complexContent>
 *     &lt;extension base="{body}bodyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="inertial" type="{body}inertialType"/>
 *         &lt;element name="joint" type="{body}jointType"/>
 *         &lt;element name="freejoint" type="{body}jointType"/>
 *         &lt;element name="geom" type="{body}geomType"/>
 *         &lt;element name="site" type="{body}siteType"/>
 *         &lt;element name="camera" type="{body}cameraType"/>
 *         &lt;element name="light" type="{body}lightType"/>
 *         &lt;element name="composite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{body}compositeType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="joint" type="{body}compositejointType"/>
 *                   &lt;element name="tendon" type="{body}tendonType"/>
 *                   &lt;element name="geom" type="{body}compositegeomType"/>
 *                   &lt;element name="site" type="{body}compositesiteType"/>
 *                   &lt;element name="skin" type="{body}skinType"/>
 *                   &lt;element name="pin" type="{body}pinType"/>
 *                   &lt;element name="include" type="{root}includeType"/>
 *                 &lt;/choice>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body" type="{}bodyarchType"/>
 *         &lt;element name="include" type="{root}includeType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyarchType", propOrder = {
    "inertialOrJointOrFreejoint"
})
public class BodyarchType
    extends BodyType
{

    @XmlElementRefs({
        @XmlElementRef(name = "light", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "geom", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "body", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "include", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "composite", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "camera", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inertial", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "joint", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "freejoint", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "site", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> inertialOrJointOrFreejoint;

    /**
     * Gets the value of the inertialOrJointOrFreejoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inertialOrJointOrFreejoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInertialOrJointOrFreejoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link LightType }{@code >}
     * {@link JAXBElement }{@code <}{@link GeomType }{@code >}
     * {@link JAXBElement }{@code <}{@link BodyarchType }{@code >}
     * {@link JAXBElement }{@code <}{@link IncludeType }{@code >}
     * {@link JAXBElement }{@code <}{@link BodyarchType.Composite }{@code >}
     * {@link JAXBElement }{@code <}{@link CameraType }{@code >}
     * {@link JAXBElement }{@code <}{@link InertialType }{@code >}
     * {@link JAXBElement }{@code <}{@link JointType }{@code >}
     * {@link JAXBElement }{@code <}{@link JointType }{@code >}
     * {@link JAXBElement }{@code <}{@link SiteType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getInertialOrJointOrFreejoint() {
        if (inertialOrJointOrFreejoint == null) {
            inertialOrJointOrFreejoint = new ArrayList<JAXBElement<?>>();
        }
        return this.inertialOrJointOrFreejoint;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{body}compositeType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="joint" type="{body}compositejointType"/>
     *         &lt;element name="tendon" type="{body}tendonType"/>
     *         &lt;element name="geom" type="{body}compositegeomType"/>
     *         &lt;element name="site" type="{body}compositesiteType"/>
     *         &lt;element name="skin" type="{body}skinType"/>
     *         &lt;element name="pin" type="{body}pinType"/>
     *         &lt;element name="include" type="{root}includeType"/>
     *       &lt;/choice>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jointOrTendonOrGeom"
    })
    public static class Composite
        extends CompositeType
    {

        @XmlElements({
            @XmlElement(name = "joint", type = CompositejointType.class),
            @XmlElement(name = "tendon", type = TendonType.class),
            @XmlElement(name = "geom", type = CompositegeomType.class),
            @XmlElement(name = "site", type = CompositesiteType.class),
            @XmlElement(name = "skin", type = SkinType.class),
            @XmlElement(name = "pin", type = PinType.class),
            @XmlElement(name = "include", type = IncludeType.class)
        })
        protected List<Object> jointOrTendonOrGeom;

        /**
         * Gets the value of the jointOrTendonOrGeom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the jointOrTendonOrGeom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJointOrTendonOrGeom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompositejointType }
         * {@link TendonType }
         * {@link CompositegeomType }
         * {@link CompositesiteType }
         * {@link SkinType }
         * {@link PinType }
         * {@link IncludeType }
         * 
         * 
         */
        public List<Object> getJointOrTendonOrGeom() {
            if (jointOrTendonOrGeom == null) {
                jointOrTendonOrGeom = new ArrayList<Object>();
            }
            return this.jointOrTendonOrGeom;
        }

    }

}
