//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.14 at 04:25:33 PM EST 
//


package org.mujoco.xml.asset;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for materialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="materialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="texture" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="texrepeat" type="{attributeTypes}twoRealsType" default="1 1" />
 *       &lt;attribute name="texuniform" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="emission" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0" />
 *       &lt;attribute name="specular" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.5" />
 *       &lt;attribute name="shininess" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.5" />
 *       &lt;attribute name="reflectance" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0" />
 *       &lt;attribute name="rgba" type="{attributeTypes}fourRealsType" default="1 1 1 1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "materialType")
public class MaterialType {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "texture")
    protected String texture;
    @XmlAttribute(name = "texrepeat")
    protected String texrepeat;
    @XmlAttribute(name = "texuniform")
    protected Boolean texuniform;
    @XmlAttribute(name = "emission")
    protected BigDecimal emission;
    @XmlAttribute(name = "specular")
    protected BigDecimal specular;
    @XmlAttribute(name = "shininess")
    protected BigDecimal shininess;
    @XmlAttribute(name = "reflectance")
    protected BigDecimal reflectance;
    @XmlAttribute(name = "rgba")
    protected String rgba;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the texture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTexture() {
        return texture;
    }

    /**
     * Sets the value of the texture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTexture(String value) {
        this.texture = value;
    }

    /**
     * Gets the value of the texrepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTexrepeat() {
        if (texrepeat == null) {
            return "1 1";
        } else {
            return texrepeat;
        }
    }

    /**
     * Sets the value of the texrepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTexrepeat(String value) {
        this.texrepeat = value;
    }

    /**
     * Gets the value of the texuniform property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTexuniform() {
        if (texuniform == null) {
            return false;
        } else {
            return texuniform;
        }
    }

    /**
     * Sets the value of the texuniform property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTexuniform(Boolean value) {
        this.texuniform = value;
    }

    /**
     * Gets the value of the emission property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmission() {
        if (emission == null) {
            return new BigDecimal("0");
        } else {
            return emission;
        }
    }

    /**
     * Sets the value of the emission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmission(BigDecimal value) {
        this.emission = value;
    }

    /**
     * Gets the value of the specular property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpecular() {
        if (specular == null) {
            return new BigDecimal("0.5");
        } else {
            return specular;
        }
    }

    /**
     * Sets the value of the specular property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpecular(BigDecimal value) {
        this.specular = value;
    }

    /**
     * Gets the value of the shininess property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShininess() {
        if (shininess == null) {
            return new BigDecimal("0.5");
        } else {
            return shininess;
        }
    }

    /**
     * Sets the value of the shininess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShininess(BigDecimal value) {
        this.shininess = value;
    }

    /**
     * Gets the value of the reflectance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReflectance() {
        if (reflectance == null) {
            return new BigDecimal("0");
        } else {
            return reflectance;
        }
    }

    /**
     * Sets the value of the reflectance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReflectance(BigDecimal value) {
        this.reflectance = value;
    }

    /**
     * Gets the value of the rgba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRgba() {
        if (rgba == null) {
            return "1 1 1 1";
        } else {
            return rgba;
        }
    }

    /**
     * Sets the value of the rgba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRgba(String value) {
        this.rgba = value;
    }

}
