# test
name: CI

on:  
   push:
       branches:
         -*

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-linux.sh

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: microsoft/setup-msbuild@v1.1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-windows.sh

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu' 
    - name: Build
      run:  bash build-mac.sh
  macM1:
    runs-on: macos-13-xlarge
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu' 
    - name: Build
      run:  bash build-mac.sh
