# test
name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'azul'
    - name: Build
      run: bash build-linux.sh

  windows:
    runs-on: windows-latest
    needs: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'azul'
    - name: Build
      run: bash build-windows.sh

  macos:
    runs-on: macos-latest
    needs: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'azul' 
    - name: Build
      run:  bash build-mac.sh