# test
name: Publish package to GitHub Packages
on:
  release:
    types: [created]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: bash build-linux.sh

  windows:
    runs-on: windows-latest
    needs: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: bash build-windows.sh

  macos:
    runs-on: macos-latest
    needs: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: echo "Not Building Macos"
      
  publish:
    runs-on: ubuntu-latest 
    needs: macos
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'azul'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION  }}