# test
name: Publish package to GitHub Packages
on: 
   push:
       tags:       
         - '*'
env:
  VERSION_SEMVER: ${GITHUB_REF##*/}
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-linux.sh
    - name: Upload math result for job Linux
      uses: actions/upload-artifact@v3
      with:
          name: linux-lib
          path: src/main/resources/linux-x86_64/libjniMuJoCoLib.so

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-windows.sh

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu' 
    - name: Build
      run: bash build-mac.sh
    - name: Upload math result for job Mac
      uses: actions/upload-artifact@v3
      with:
          name: mac-lib
          path: src/main/resources/macosx-x86_64/libjniMuJoCoLib.dylib
  publish:
    runs-on: ubuntu-latest 
    needs: [macos,windows,linux]
    permissions: 
      contents: write
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          VERSION_SEMVER: ${{ steps.vars.outputs.tag }}
        run: |
          echo $VERSION_SEMVER
          echo ${{ steps.vars.outputs.tag }}
      - name: Download math result for job Linux
        uses: actions/download-artifact@v3
        with:
          name: linux-lib  
      - name: Download math result for job Mac
        uses: actions/download-artifact@v3
        with:
          name: mac-lib
      - name: Print Working Dir
        run: |
             ls -al .
             mkdir -p src/main/resources/macosx-x86_64/
             mkdir -p src/main/resources/linux-x86_64/
             mv libjniMuJoCoLib.dylib src/main/resources/macosx-x86_64/
             mv libjniMuJoCoLib.so src/main/resources/linux-x86_64/
                 
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: jar publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_SEMVER: ${{ steps.vars.outputs.tag }}
          
      - name: Make gitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
               draft: false
               prerelease: false
               release_name: ${{ steps.version.outputs.version }}
               tag_name: ${{ github.ref }}
        env:
               GITHUB_TOKEN: ${{ github.token }}
               
      - name: upload MuJoCo jar artifact
        uses: actions/upload-release-asset@v1
        env:
               GITHUB_TOKEN: ${{ github.token }}
        with:
               upload_url: ${{ steps.create_release.outputs.upload_url }}
               asset_path: ./build/libs/mujoco-java.jar
               asset_name: mujoco-java.jar
               asset_content_type: application/jar          
          
