# test
name: Publish package to GitHub Packages
on: 
   push:
       tags:       
         - '*'
env:
  VERSION_SEMVER: ${GITHUB_REF##*/}
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-linux.sh

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu'
    - name: Build
      run: bash build-windows.sh

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
          java-version: '8'
          distribution: 'zulu' 
    - name: Build
      run: bash build-mac.sh
      
  publish:
    runs-on: ubuntu-latest 
    needs: [macos,windows,linux]
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Verify data
        run: echo "User $GITHUB_ACTOR version $VERSION_SEMVER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        
      - name: Publish package
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: jar publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
